version: '3.7'

services:
  fluent-bit:
    build:
      context: extensions/fluent-bit/
      args:
        FLUENT_BIT_VERSION: ${FLUENT_BIT_VERSION}
    user: root
    command:
      - /fluent-bit/bin/fluent-bit
      - --config=/etc/fluent-bit/fluent-bit.conf
    volumes:
      - ./extensions/fluent-bit/config/:/etc/fluent-bit/:ro
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    environment:
      FLUENT_BIT_INTERNAL_PASSWORD: ${FLUENT_BIT_INTERNAL_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch
